---
  name: checks

  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_call:

  jobs:
    checks:
      name: Running checks
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.11"]

      steps:
        - name: Checking out repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 1

        - name: Setting up PDM @ ${{ matrix.python-version }}
          uses: pdm-project/setup-pdm@v3
          with:
            python-version: ${{ matrix.python-version }}
            cache: true
            architecture: x64
            enable-pep582: true

        - name: Check lockfile
          run: pdm lock --check

        - name: Installing dependencies
          run: pdm install

        - name: Code checking using ruff
          run: pdm run ruff check .

        - name: Type checking using mypy
          run: pdm run mypy .
