---
  name: Build and push docker image

  on:
    push:
      branches:
        - main
      tags:
        - "*.*.*"

  env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

  jobs:
    build-docker-image:
      name: Build docker image
      uses: ./.github/workflows/build-docker-image.yml
      secrets:
        WORKFLOW_ASSISTANT_APP_ID: ${{ secrets.WORKFLOW_ASSISTANT_APP_ID }}
        WORKFLOW_ASSISTANT_PRIVATE_KEY: ${{ secrets.WORKFLOW_ASSISTANT_PRIVATE_KEY }}

    push-image:
      name: Push docker image
      runs-on: ubuntu-latest
      needs: [build-docker-image]
      permissions:
        contents: read
        id-token: write
        attestations: write
        packages: write

      steps:
        - name: Install cosign
          if: github.event_name != 'pull_request'
          uses: sigstore/cosign-installer@v3.7.0

        - name: Setup docker buildx
          uses: docker/setup-buildx-action@v3.8.0

        - name: Log into registry ${{ env.REGISTRY }}
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v3.3.0
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Get access token
          id: get_access_token
          uses: peter-murray/workflow-application-token-action@v4.0.0
          with:
            application_id: ${{ secrets.WORKFLOW_ASSISTANT_APP_ID }}
            application_private_key: ${{ secrets.WORKFLOW_ASSISTANT_PRIVATE_KEY }}
            revoke_token: true

        - name: Push docker image
          id: push
          uses: docker/build-push-action@v6.12.0
          with:
            tags: ${{ needs.build-docker-image.outputs.tags }}
            labels: ${{ needs.build-docker-image.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
            push: true
            secrets: |
              "github_token=${{ steps.get_access_token.outputs.token }}"
